<a href="https://colab.research.google.com/github/kandybenko/Projects/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%E2%84%965_%D0%91%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82_%D0%B4%D0%BB%D1%8F_SQL_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Введение и соединение с БД в Python**

1. Для работы в данном ноутбуке необходимо авторизироваться в google.
2. Сохранить себе блокнот на диск можно нажав "Файл" -> "Сохранить блокнот на диске"

## **ВНИМАНИЕ!** ПЕРЕД РАБОТОЙ С ДАННЫМ СКРИПТОМ НУЖНО НАЖАТЬ КНОПКУ "ВЫПОЛНИТЬ ВСЕ"

Данный скрипт предназначен для завершения практики №5 по выборке данных ecommerce.sqlite без DBeaver

In [ ]:
# Скачаем данные с репозитория
!wget -O ecommerce.sqlite 'https://downloader.disk.yandex.ru/disk/a2f7a8ac10e860ecc92a24f44e9b5640ba7d3381b5f0ce6a50c773354fb77223/68fa4ae9/oHFRXlaY9N2N30LOEB9ZWb5KE7LYLeVICoF_hzm0p3DzfpscruDZFB5WZkP5ITCU0Vi-CBDRBC3zP1sS0gCVQQ%3D%3D?uid=0&filename=ecommerce.sqlite&disposition=attachment&hash=67tXoBR%2BP2vcSRZFNVZWJwWaWHKLqcHkfSiAIe2QpZ6PzL7ZxEXnfBZWy5i235fQq/J6bpmRyOJonT3VoXnDag%3D%3D%3A&limit=0&content_type=application%2Fvnd.sqlite3&owner_uid=335339673&fsize=210706432&hid=cc4c1612206a1153ceec2114d8db3fd6&media_type=unknown&tknv=v3' --quiet

In [ ]:
# Обозначим в переменную путь к БД
path_db = "/content/ecommerce.sqlite"

In [ ]:
import sqlite3
from pathlib import Path
import pandas as pd

# путь к файлу БД
db_path = Path(path_db)  # ваш файл

# 1. подключение (создаст файл, если его нет)
con = sqlite3.connect(db_path)

# 2. полезно: включить внешние ключи и доступ к колонкам по имени
con.execute("PRAGMA foreign_keys = ON;")
con.row_factory = sqlite3.Row  # строки как dict-похожие объекты

# **Соединение с БД в Python**

## **Задание №1.** Помесячный GMV и активность в 2017

Нужно посчитать для каждого месяца 2017 года совокупный оборот продаж и активность заказов. Под «оборотом» (GMV) понимается сумма стоимостей товарных позиций, входящих в заказы за этот месяц; стоимость позиции берётся из цены самой позиции и суммируется по всем позициям, относящимся к заказам, оформленным в соответствующем месяце. Для активности требуется вывести количество уникальных заказов и количество товарных позиций в этих заказах.

В отчёт попадают только заказы с операционными статусами, предполагающими реальное движение товара (например, оформлен, одобрен, в процессе, выставлен счёт, отправлен, доставлен) `('delivered','shipped','invoiced','processing','created','approved')`. Месяц определяется по дате покупки заказа и выводится в формате «ГГГГ-ММ».

Итог должен содержать по одной строке на месяц с тремя показателями: число заказов, число позиций и GMV, отсортирован по возрастанию месяца.

In [ ]:
# Внутри скобок """ """ ваш запрос,
# Выполнение ячейки на кнопку сбоку или (CTRL+ENTER)
query = """
    SELECT *
    FROM orders;
"""

pd.read_sql(query, con)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

## **Задание №2**. ТОП-10 категорий по выручке, с переводом

Нужно определить десять товарных категорий с наибольшим оборотом продаж. Для каждой категории требуется посчитать сумму цен всех проданных позиций (это и есть выручка/GMV категории), количество уникальных заказов, в которых встречались товары этой категории, и общее число товарных позиций.

Дополнительно к исходному названию категории нужно вывести её англоязычный перевод из словаря переводов.

Итоговый набор данных должен быть отсортирован по выручке по убыванию и ограничен первыми десятью строками.

In [ ]:
# Внутри скобок """ """ ваш запрос,
# Выполнение ячейки на кнопку сбоку или (CTRL+ENTER)
query = """
    SELECT 1;
"""

pd.read_sql(query, con)

   1
0  1

## **Задание №3**. Средняя фактическая скорость доставки по штатам

Нужно оценить скорость доставки в разрезе штатов, где проживают клиенты.

Для каждого штата считается средняя длительность от момента покупки заказа до фактической доставки клиенту в днях.

В расчёт включаются только те заказы, которые действительно были доставлены и для которых известна фактическая дата получения клиентом.

Помимо средней длительности нужно вывести количество доставленных заказов, учтённых в расчёте.

Результат необходимо отсортировать по возрастанию средней длительности доставки.

In [ ]:
# Внутри скобок """ """ ваш запрос,
# Выполнение ячейки на кнопку сбоку или (CTRL+ENTER)
query = """
    SELECT 1;
"""

pd.read_sql(query, con)

   1
0  1

## **Задание №4**. Просрочка относительно обещанной даты

Нужно сравнить обещанные сроки и фактические сроки доставки.

Для каждого штата клиентов рассчитывается средняя величина отклонения (в днях) между фактической датой доставки и обещанной датой доставки:
* *положительное* значение означает опоздание,
* *отрицательное* — доставку раньше обещанного.

Дополнительно требуется посчитать долю заказов с опозданием, то есть долю случаев, когда фактическая дата позже обещанной.

В отчёт включаются только заказы с известной фактической датой доставки.

Для каждого штата выводятся средняя просрочка, доля опоздавших заказов и количество наблюдений, а результат сортируется по доле опозданий (по убыванию), а затем по величине средней просрочки.

In [ ]:
# Внутри скобок """ """ ваш запрос,
# Выполнение ячейки на кнопку сбоку или (CTRL+ENTER)
query = """
    SELECT 1;
"""

pd.read_sql(query, con)

   1
0  1

## **Задание №5**. Повторные покупки, доля повторных клиентов

Нужно оценить повторность покупок.

Сначала для каждого клиента считается, сколько заказов он оформил за всё время наблюдений.

Затем по всему множеству клиентов вычисляется:
* общее число клиентов;
* число клиентов, сделавших как минимум два заказа;
* доля таких клиентов от общего числа.

В итоговой строке должны быть три показателя: всего клиентов, клиентов-повторителей и их доля (в десятичных дробях или процентах — на ваш выбор, но последовательно в одном формате).

In [ ]:
# Внутри скобок """ """ ваш запрос,
# Выполнение ячейки на кнопку сбоку или (CTRL+ENTER)
query = """
    SELECT 1;
"""

pd.read_sql(query, con)

   1
0  1

## **Задание №6**. Эффективность продавцов

Нужно получить рейтинг продавцов по активности и базовым бизнес-показателям.

Для каждого продавца считается количество уникальных заказов, в которых он участвовал, число уникальных клиентов, которым он продал хотя бы одну позицию, общее число проданных товарных позиций, совокупный оборот по этим позициям (сумма цен) и средняя стоимость доставки на позицию (среднее от значений стоимости фрахта по позициям).

Затем формируется топ-10 продавцов, отсортированный по числу заказов по убыванию.

В отчёте по каждому продавцу должны присутствовать перечисленные метрики.

In [ ]:
# Внутри скобок """ """ ваш запрос,
# Выполнение ячейки на кнопку сбоку или (CTRL+ENTER)
query = """
    SELECT 1;
"""

pd.read_sql(query, con)

   1
0  1

## **Задание №7**. Платёжное поведение

Нужно сравнить используемые способы оплаты.

По каждому типу оплаты требуется вывести количество зарегистрированных платежей, среднее число рассрочек (если применимо), средний размер платежа и долю заказов, в которых встречается данный способ оплаты.

Под долей заказов понимается отношение числа уникальных заказов, где зафиксирован хотя бы один платёж данного типа, к общему числу уникальных заказов, по которым известны записи об оплате.

Следует учитывать, что у одного заказа может быть несколько платежей.

Доля считается на уровне «есть/нет» для типа оплаты в заказе.

In [ ]:
# Внутри скобок """ """ ваш запрос,
# Выполнение ячейки на кнопку сбоку или (CTRL+ENTER)
query = """
    SELECT 1;
"""

pd.read_sql(query, con)

   1
0  1

## **Задание №8**. Зависимость оценки от скорости доставки

Нужно изучить, как длительность доставки коррелирует с оценками в отзывах.

Для каждого заказа с отзывом и известной фактической датой доставки рассчитывается длительность доставки в днях как разница между датой доставки клиенту и датой покупки.

Далее каждый заказ попадает в один из трёх интервалов длительности:
* до пяти дней включительно,
* от шести до десяти дней включительно,
* более десяти дней.

Для каждого интервала требуется посчитать количество заказов и среднюю оценку из отзывов.

Итог должен содержать три строки — по одному агрегату на интервал — в логическом порядке от самого быстрого интервала к самому длительному.

In [ ]:
# Внутри скобок """ """ ваш запрос,
# Выполнение ячейки на кнопку сбоку или (CTRL+ENTER)
query = """
    SELECT 1;
"""

pd.read_sql(query, con)

   1
0  1

## **Задание №9.** Когорты по месяцу первой покупки

Нужно определить объём «новых» клиентов по месяцам. Для каждого клиента находится дата его самой первой покупки за весь период наблюдений. Затем клиенты группируются по месяцу этой первой покупки (месяц берётся из даты первой покупки в формате «ГГГГ-ММ»), и по каждому месяцу считается количество клиентов, совершивших свою первую покупку именно в этом месяце.

Результат должен представлять собой временной ряд «месяц — число новых клиентов», отсортированный по возрастанию месяца.

In [ ]:
# Внутри скобок """ """ ваш запрос,
# Выполнение ячейки на кнопку сбоку или (CTRL+ENTER)
query = """
    SELECT 1;
"""

pd.read_sql(query, con)

   1
0  1

## ***Задание №10***. География продавцов и доставленные заказы

Нужно оценить концентрацию продавцов по городам и их реальный вклад в доставленные заказы.

Для каждого города, где зарегистрированы продавцы, сначала считается количество уникальных продавцов. Затем по тому же городу определяется, сколько уникальных заказов с фактической доставкой было обслужено продавцами из этого города (каждый доставленный заказ учитывается один раз, даже если в нём присутствуют позиции нескольких продавцов из одного и того же города).

Итоговый отчёт должен быть отсортирован по числу продавцов по убыванию, при равенстве — по числу доставленных заказов по убыванию, и ограничен первыми десятью городами.

In [ ]:
# Внутри скобок """ """ ваш запрос,
# Выполнение ячейки на кнопку сбоку или (CTRL+ENTER)
query = """
    SELECT 1;
"""

pd.read_sql(query, con)

   1
0  1

## **Задание №11**. ABC анализ товаров

Провести ABC анализ категорий товаров `products` по совокупным продажам за весь период. Группу A присвоить наиболее продаваемым товарам, принесшим 70% совокупной прибыли, группу B присвоить товарам менее продаваемым, принесшим 25% совокупной прибыли и остальные товары, принесшие остальные 5% прибыли.

In [ ]:
# Внутри скобок """ """ ваш запрос,
# Выполнение ячейки на кнопку сбоку или (CTRL+ENTER)
query = """
    SELECT 1;
"""

pd.read_sql(query, con)

   1
0  1

## **Задание №12**. XYZ анализ товаров

Провести XYZ анализ категорий товаров `products` по помесячной динамике их продаж на весь период.

In [ ]:
# Внутри скобок """ """ ваш запрос,
# Выполнение ячейки на кнопку сбоку или (CTRL+ENTER)
query = """
    SELECT 1;
"""

pd.read_sql(query, con)

   1
0  1

## **Задание №13**. RFM анализ клиентов

Провести RFM анализ клиентов, рассчитав как обычные классы R F M по отдельности, так и определить RFM метрику $RFM = (F * \sqrt{M}) / (R + 1)$ на основе которой также можно произвести классификацию когорт.

In [ ]:
# Внутри скобок """ """ ваш запрос,
# Выполнение ячейки на кнопку сбоку или (CTRL+ENTER)
query = """
    SELECT 1;
"""

pd.read_sql(query, con)

   1
0  1